apiVersion: 1

datasources:
  - name: clickhouse
    type: grafana-clickhouse-datasource
    jsonData:
      port: 9000
      server: clickhouse
      username: admin
      tlsSkipVerify: true
    secureJsonData:
      password: admin
